### ISSUE TITLE
lome6 broken since ce9a803e3e9c51b485551d004f5c93705648ce17

### ISSUE THREAD

**Issue by eku** [ethersex/ethersex#346]
Trying to compile Ethersex firmware using profile 'scripts/profiles/lome6' ...
services/lome6/lome6.c: In function 'lome6_get_temperature':
services/lome6/lome6.c:42:18: error: incompatible types when initializing type 'uint16_t' using type 'ow_temp_t'
  uint16_t temp = ow_temp_normalize(rom, &sp);
                  ^
