### ISSUE TITLE
ecmd_sender_state.h:32:5: error: expected specifier-qualifier-list before ‘client_return_text_callback_t’

### ISSUE THREAD

**Issue by macmattes** [ethersex/ethersex#421]
In file included from ./meta.h:9:0,
                 from ./protocols/uip/uip.h:59,
                 from ./protocols/ecmd/sender/ecmd_sender_net.h:30,
                 from control6/control6.c:14:
./protocols/ecmd/sender/ecmd_sender_state.h:32:5: error: expected specifier-qualifier-list before ‘client_return_text_callback_t’

mit zbus enabled auf uart1 gibt es obigen fehler, sorry wenns zu knapp ist, ich kann es nicht besser beschreiben, so weit ich gesehen hab gab es im April ein update in der datei, seit dem oder danach ist der fehler reingekommen

**Comment by eku** [comment]
git bisect ?

**Comment by macmattes** [comment]
was? hab mir gerade mal ne frische git version gezogen und nur meine
configs zusammengestellt. kommt der gleiche fehler, gibt es da ne datei die
weiterhelfen könnte?
habe ethernet forwarding auf zbus und ecmd send tcp und udp, dann noch i2c,
onewire und dht
liegt anscheinend an control6, hab es mit einer leeren control6 versucht,
auch wieder der fehler
In file included from ./meta.h:9:0,
                 from ./protocols/uip/uip.h:59,
                 from ./protocols/ecmd/sender/ecmd_sender_net.h:30,
                 from control6/control6.c:14:
./protocols/ecmd/sender/ecmd_sender_state.h:32:5: error: expected
specifier-qualifier-list before ‘client_return_text_callback_t’
In file included from control6/control6.c:52:0:
./hardware/lcd/hr20.h:27:1: error: expected expression before ‘void’
und ein fehler mehr, ohne control6 rennt er anstandslos durch


2015-09-01 19:39 GMT+02:00 Erik Kunze <notifications@github.com>:

**Comment by eku** [comment]
Wenn Du schon nicht gewillt bist, mittels 'git bisect' den verursachenden Commit zu bestimmen, dann häng wenigstens Deine aufoconf.h an.

**Comment by macmattes** [comment]
ah so, wusste nicht was gewiollt war, bin nicht so fit sorry.
gibt alles heute abend wenn ich zuhause bin

**Comment by macmattes** [comment]
hallo, hab nun null ahnung wie man bisect bedient start/good/bad/run? Hab
mal was probiert
start:
Already on 'master'
git bisect good
git bisect bad
1f115abc3c215ec872de3a50261a6c1ad1076c00 was both good and bad

wie gesagt es rennt durch wenn control6 ausgeschaltet ist und nicht wenn
control an ist

Am 2. September 2015 um 07:53 schrieb Erik Kunze <notifications@github.com>:

**Comment by eku** [comment]
Was steht in deinen C6 script?

**Comment by macmattes** [comment]
nur noch 
CONTROL_START

CONTROL_END

hab es sogar mal mit einer ganz leeren datei versucht, die geht auch nicht

**Comment by eku** [comment]
Ich habe auch die HR20 Config ausgewählt unde Send ECMD hinzugenommen und es übersetzt. Bitte Dein .config anhängen.

**Comment by macmattes** [comment]
die config



Am 2. September 2015 um 18:06 schrieb Matthias Berner <mattes.b@gmx.net>:

**Comment by macmattes** [comment]
komisch ich hab sie in der mail angehangen

**Comment by eku** [comment]
Welche Email? Du kannst Dateien hier ans Issue anhängen ("select item") oder nutze gist.gitgub.com.

**Comment by macmattes** [comment]
die config lässt sich hier nicht hochladen, es wird ein bild erwartet, hab mal gist versucht, hoffe das war so richtig. ich hatte auf ein mail dass ich von Github bekommen hatte mit der config geantwortet, text steht oben aber der anhang kam wohl nicht durch

https://gist.github.com/macmattes/6572cd663b157dba0081#file-config

**Comment by eku** [comment]
@macmattes: bitte um Rückmeldnung, ob der Patch das Problem bei Dir behebt.

**Comment by macmattes** [comment]
Hallo
ja , läuft durch, danke
