### ISSUE TITLE
GCC 10.1 compatibility

### ISSUE THREAD

**Issue by eku** [ethersex/ethersex#572]
## Describe the bug

Using the ```lome6``` module produces lots of linker errors with GCC 10.1.

## To Reproduce

Configure with profile ```scripts/profiles/lome6``` and compile using GCC 10.1

## Actual behavior

Lots of linker errors
```
multiple definition of
```
## Expected behavior

Compiles and links.

## Ethersex version

e1768307fa6a9a0253e24dd8ab658a13b5abbe81

## Hardware

N/A

## Additional context

N/A
